services:
  database:
    container_name: fp-database
    restart: unless-stopped
    image: postgres:latest
    environment:
      POSTGRES_DB: fp
      POSTGRES_USER: bambang
      POSTGRES_PASSWORD: bambang123
    ports:
      - 5432:5432
    volumes:
      - ./docker/volumes/:/var/lib/postgresql
    networks:
      - fp-network

networks:
  fp-network:
    driver: bridge

volumes:
  mysqldata: